### ISSUE TITLE
Radiance 5.0 win32 use 64bit QT 5

### ISSUE THREAD

**Issue by tumagonx** [NREL/Radiance#10]
I try to run on Windows 32 bit and see error when run rvu.exe, using dependencywalker I found out that bundled Qt was 64bit dlls while radiance was 32bit.

**Comment by mostaphaRoudsari** [comment]
cc: @rpg777

**Comment by rpg777** [comment]
Thanks @tumagonx and @mostaphaRoudsari for letting us know. We'll look into it.

**Comment by rpg777** [comment]
@tumagonx, have a look at the latest NREL Radiance release (5.0.a.8) for a true 32-bit Windows rvu!
