### ISSUE TITLE
tiff directory missing?

### ISSUE THREAD

**Issue by manish-grafty** [NREL/Radiance#18]
I am facing compile issues while running makeall install from the top level.

OS: ubuntu 16.04

Issue #1: Seems like tiff and its subdirectories are missing? I ran a git submodule update --recursive --remote to make sure that I am not missing any submodules, but no luck. Can you please check and suggest? Logs below.

Issue #2: Version.c compile fails. Logs below:

=== Issue #1 Logs: ====
/home/ubuntu/radiance/Radiance/src/px /home/ubuntu/radiance/Radiance/src 
In directory px...
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO   -c -o pfilt.o pfilt.c
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO   -c -o pf2.o pf2.c
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO   -c -o pf3.o pf3.c
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO -o pfilt pfilt.o pf2.o pf3.o -lrtrad -lm
pfilt.o: In function `main':
pfilt.c:(.text.startup+0x823): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO   -c -o ttyimage.o ttyimage.c
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO -o ttyimage ttyimage.o -lrtrad -lm
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO   -c -o psign.o psign.c
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO -o psign psign.o -lrtrad -lm
cd tiff ; ./configure -C -quiet -with-CC=gcc \
	"--libdir=`pwd`/../../lib" "--includedir=`pwd`/../../common" \
	--enable-static --disable-shared --disable-cxx \
	--enable-logluv --disable-jpeg \
	--disable-zlib --disable-pixarlog \
	"-with-ENVOPTS=-O2" ; \
cd port ; make all ; \
cd ../libtiff ; make install
/bin/sh: 1: cd: can't cd to tiff
/bin/sh: 1: ./configure: not found
/bin/sh: 7: cd: can't cd to port
make[1]: Entering directory '/home/ubuntu/radiance/Radiance/src/px'
make[1]: *** No rule to make target 'all'.
make[1]: Leaving directory '/home/ubuntu/radiance/Radiance/src/px'
/bin/sh: 8: cd: can't cd to ../libtiff
make[1]: Entering directory '/home/ubuntu/radiance/Radiance/src/px'
make[1]: *** No rule to make target 'install'.
make[1]: Leaving directory '/home/ubuntu/radiance/Radiance/src/px'
Rmakefile:141: recipe for target '../lib/libtiff.a' failed
make: *** [../lib/libtiff.a] Error 2

==== Issue #2 logs ====
cp ../rt/Version.c .
gcc -I../common -L../lib -O2 -Dlinux -D_FILE_OFFSET_BITS=64 -L/usr/X11R6/lib -I/usr/include/X11 -DNOSTEREO -DDEVPATH=\"/usr/local/bin\"   -c -o Version.o Version.c
Version.c:1:10: error: invalid suffix "a" on floating constant
 RADIANCE 5.2a
          ^
Version.c:1:10: error: expected '=', ',', ';', 'asm' or '__attribute__' before numeric constant
<builtin>: recipe for target 'Version.o' failed
make: *** [Version.o] Error 1

**Comment by rpg777** [comment]
The supplemental tiff libraries are not part of the source repo. The Radiance CMake system has been vastly improved to auto-download/build libtiff for you, if you wish to use that system. If you want to use the makeall script, you'll need to get and unpack the radiance supplemental files archive from radiance-online, [here](https://www.radiance-online.org/download-install/radiance-source-code/latest-release).
