### ISSUE TITLE
radiance rvu.exe error

### ISSUE THREAD

**Issue by inkmug** [NREL/Radiance#19]
Hi, I'm trying to run rvu.exe but come across this error
"The procedure entry point ?trimmed_helper@QString@@CA?AV1@AEAV1@@Z could not be located in the dynamic link library Qt5Core.dll".

![radiance_rvu_error](https://user-images.githubusercontent.com/5752865/31104360-660d0eb6-a791-11e7-9b7c-f15db26596a7.png)
The Radiance version I use is 5.1. Window 7 Enterprise 64 bit.
Any possible causes? 
Thanks.

**Comment by rpg777** [comment]
This has been fixed in the latest (and hopefully ongoing) installer(s).
