### ISSUE TITLE
glarendx.c bug causing NaNs

### ISSUE THREAD

**Issue by ARCowie28** [NREL/Radiance#20]
I was getting NaNs from glare analysis, and traced the problem to what appears to be a bug in reading glare sources in glarendx.c, function read_input, line 208:

<p><code>
			if (sscanf(buf, FVFORMAT, &gs->dir[0], &gs->dir[1],
						&gs->dir[2]) != 3 ||
					sscanf(buf, "%lf %lf",
						&gs->dom, &gs->lum) != 2)
</code></p>

The buffer <code>buf</code> does not remember the position from the first sscanf, so <code>dom</code> and <code>lum</code> take on the first two values of the direction vector.

I changed this code to match code doing the same thing in xglaresrc.c, function circle_sources, line 208:

<p><code>
	if (sscanf(linbuf, "%lf %lf %lf %lf %lf",
					&dir[0], &dir[1], &dir[2],
					&dom, &lum) != 5)
</code></p>

This seemed to fix the problem.

I decided to raise this as an issue rather than just upload the fix because I figured a change like this merited the scrutiny of more experienced Radiance devs.

Cheers,
Andy Cowie

**Comment by rpg777** [comment]
Fixed with this [commit](https://github.com/NREL/Radiance/commit/6d26f1777d6addf1bd8cb51fd9ffeebb6a0998f6)

**Comment by rpg777** [comment]
Thanks @ARCowie28, in the future please post questions and bugs to the radiance-dev list; that's where the Radiance developer will see these.
