### ISSUE TITLE
is it possible to change the name of the RAYPATH environment variable?

### ISSUE THREAD

**Issue by philipschwarz** [NREL/Radiance#25]
Hello.

Is it possible to change the name of the RAYPATH environment variable without having to recompile radiance? I would like to be able to have two coexisting radiance instances, one using RAYPATH and another using RAY_PATH. Is that possible? The first instance already exists and was compiled from source code, so uses RAYPATH. I would like to install another version of radiance that uses RAY_PATH instead.

If not, then for the second instance I would have to manually change the name of the variable in the codebase and then compile radiance from source.

I see that the build process (e.g. makeall) uses csh. What if I don't have csh available and cannot install it. Would it be possible to modify the build process to use tcsh instead (which I have available?). If not, is it possible to compile radiance using gcc or tcsh without using makeall?

Thank you in advance for your help

**Comment by philipjss** [comment]
It looks like I may not even have tcsh available. Is it possible to compile radiance using gcc?

**Comment by philipschwarz** [comment]
More constraints: I don't have tcsh available. Is it possible to build radiance using gcc, i.e. without using 'makeall install', since the latter uses csh? I am trying to build radiance inside a Linux docker container where csh/tcsh are not available but gcc is?

Alternatively, is it possible to use 'makeall install' to cross compile? i.e. to run 'makeall install' on a Mac but create binaries for Linux 64?

**Comment by rpg777** [comment]
These questions should really be asked in the radiance-general and/or radiance-dev mailing lists. This is a mirror of the Radiance source code repository, and not really an active issue tracker. Besides, these questions are not related to issues or bugs. 

Short answers anyway: I would recommend redefining RAYPATH when you use the different instances of Radiance you have installed, and of course you can use gcc; the makefiles are all set up to use gcc, and there is also a full CMake build system in the repository so you could use CMake as well. You're barking up a nasty, heavy tree trying to cross compile for Linux from Mac tho. Recommend you set up a Linux VM on that Mac to make your 64-bit Linux builds. 

Again, I recommend you repost these questions to radiance-dev; that's where the Radiance developer and user communities are, and these questions and answers will enrich that database.
