### ISSUE TITLE
problem found when using findglare 

### ISSUE THREAD

**Issue by ChenWenQian** [NREL/Radiance#27]
A warning occurred when i using findglare to create a glr file for calculating Daylight Glare Index：“rtrace：No light source was found in octree ”，however，when I create a sky with sun，It didn't show up. 
But I want to calculate the DGI under overcast sky（no direct sunlight），I don't know how to sovle this problem！！！
Another issue is that “Nan”occurred when calculating DGI or CIE Glare index. 

Great thanks if anyone can help me.

cheers，
CHEN

**Comment by rpg777** [comment]
Not a code issue. This is a topic for the user forums, either Radiance Discourse or UnmetHours (which I think you've already taken this to, and had resolved (i.e., this warning is normal for overcast skies because there *are* no (direct) light sources in them)).
