### ISSUE TITLE
Redefinition of open may be confusing!

### ISSUE THREAD

**Issue by germolinal** [NREL/Radiance#28]
Hello, 

I am working with Radiance libraries and Files in another project. And I was having an issue with the redefinition of open to _open in Windows that happens [HERE](https://github.com/NREL/Radiance/blob/8859c0706d89adada8cdad199f66477490b66758/src/common/platform.h#L18). It bothers because open is the name of a method that I use [HERE ](https://github.com/GroundhogLighting/emp_core/blob/d905cebaedf12d0901336e9089c5083d04583f69/src/calculations/radiance.cpp#L91)(which may be pretty common).

It is not really a big deal, as I solved it using [THIS](https://stackoverflow.com/questions/1543736/how-do-i-temporarily-disable-a-macro-expansion-in-c-c). However, it may be confusing to redefine names as common as those.

Proposition: Use some other name, like RAD_OPEN or something like this.

I did not create a pull request because I am not sure how many other lines of code will that mess up.

Best!

**Comment by rpg777** [comment]
Thanks @germolinal. Be advised, this issues tab is not watched by Greg (and apparently not too carefully by me either), so you may want to post this discussion on the discourse site too.

**Comment by germolinal** [comment]
Thanks, Rob!
