### ISSUE TITLE
why did the illuminance results become so much higher when put several points together 

### ISSUE THREAD

**Issue by ChenWenQian** [NREL/Radiance#31]
I create a txt file containing the coordinates of four points in a room, why did the illuminance results become so much higher ?  The simulation results were several times of the results when I used individual txt file for a point. 
For example, for calculation of the illuminance of four points in a room, first I create four txt files containing the coordinates, the results were around 100 lux,  but then, I put the coordinates of the four points in a single txt file (one point in each line),  the results were around 800-1000lux.

I don't know why? Any suggestions would be appreciated. Thank you.

**Comment by rpg777** [comment]
This is not the place for posting general support/use questions. Please see the [Radiance Discourse Forum](https://discourse.radiance-online.org/).
