### ISSUE TITLE
bifacial_radiance.py missing

### ISSUE THREAD

**Issue by nplola** [NREL/Radiance#34]
Hi,

I just installed followed instructions from the installation guide by Silvana Ayala. It seems it all went well but when I run Spyder and tried to open the bifacial_radiance.py file I noticed the Bifacial_radiance-master folder I unzipped is missing it. Instead I could see some other .py files that are not shown in the video.

![bf_r folder](https://user-images.githubusercontent.com/53555717/62273099-00be7f80-b43d-11e9-8b89-22a118f968ba.JPG)

Does it have something to do with being a new release? Can you help me, please?

Thank you.

**Comment by mostaphaRoudsari** [comment]
I believe you are posting your problem in the wrong place. This repository is for radiance iteself and not bifacial.

**Comment by nplola** [comment]
Then... can you tell me where can I post this issue, please?

**Comment by mikofski** [comment]
@nplola please post your issue at [bifacial_radiance](../../bifacial_radiance), and close this one here. Thanks! This is the repository for RADIANCE, not bifacial-radiance, which only uses RADIANCE for ray-tracing calculations.

However, I think I can answer your question and save you time. there is no module called `bifacial_radiance.py`, instead it is a Python package - you can examine the [bifacial-radiance master tree](../../bifacial_radiance/tree/master/bifacial_radiance) to see for yourself.

So to solve your problem and continue with the instructions, simply MOVE ONE FOLDER BACK UP, then follow the directions. EG: in a terminal:

    path/to/bifacial_radiance $ ls

    bifacial_radiance    <-- this is the Python package
    docs
    MANIFEST.in
    pytest.ini
    requirements.txt
    setup.py
    versioneer.py
    LICENSE
    README.md
    setup.cfg
    tests

    path/to/bifacial_radiance$ ipython

    IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

    In [1]: import bifacial_radiance

    In [2]: bifacial_radiance.gui()
