### ISSUE TITLE
Request for gui implementation of 2P fixed tilt structure with Purlins

### ISSUE THREAD

**Issue by Pk-nordic** [NREL/Radiance#39]
Typical 2P fixed tilt structures have purlins and not just a torque tube. Any chance this mounting design will also be implemented in the gui ?

**Comment by mostaphaRoudsari** [comment]
Hi @Pk-nordic - most likely you are posting this question here by mistake but even if it is a question for Radiance then you should post it on the forum: https://discourse.radiance-online.org/ - Greg doesn't see the issues on this Repository.

Finally, this repository is outdated and I hope someone at NREL makes it private or changes it to read-only. The updated repository is here: https://github.com/LBNL-ETA/Radiance/tree/master

**Comment by Pk-nordic** [comment]
My bad.
