### ISSUE TITLE
How to create an 10.000 lux overcast grey sky?

### ISSUE THREAD

**Issue by redinkinc** [NREL/Radiance#5]
Hello Again,
everything works fine so far, but as I now want to get the illuminance in a room I followed the radiance_tutorial and end up in the following problem: When I use the provded sky.rad and create the sky.mat using gensky as described in the tutorial, I result in the following:

> $ echo 0 0 0 0 0 1 | rtrace -I -ab 1 octrees\sky.oct
#?RADIANCE
oconv skies\sky_10klx.mat skies\sky.rad
rtrace -I -ab 1
SOFTWARE= RADIANCE 4.2a lastmod  by  on w015t-001
CAPDATE= 2015:09:15 11:56:42
GMT= 2015:09:15 09:56:42
FORMAT=ascii
4.751300e+001   5.813355e+001   6.707717e+001

and 
> echo 0 0 0 0 0 1 | rtrace -I -h -ab 1 octrees\sky.oct | rcalc -e "$1=179*(.265*$1+.670*$2+.065*$3)"
10025.4983

This is as near as I can get, but the sky is not grey. Can anyone provide me with an answer?
Thanks, Fabian

**Comment by mostaphaRoudsari** [comment]
Hi Fabian, Github is not the best medium to ask such questions. I would suggest you to post them on unmethours.com and tag them as radiance. The right people will be able to get back to you on the list.

**Comment by redinkinc** [comment]
Thanks @mostaphaRoudsari. tried to post there but cannot sign up. Will close this issue anyway...
Fabian
