### ISSUE TITLE
run oconv with standard input from process

### ISSUE THREAD

**Issue by redinkinc** [NREL/Radiance#6]
Hi guys,
I startet programming my own radiance library in C# and ended up with the following problem:
I create my sky, materials and object as strings. When I write this string into a file and then run oconv to create the the octree everything works fine. If I copy/paste the string to the windows cmd using the oconv options "-f -" also everything is fine. But when I start oconv as a process and pass the string to the StandardInput, the octree is generated without warnings but rtrace returns "fatal: truncated octree".
Has anyone an idea where the problem might be?
thanks, fabian

**Comment by MatthewSteen** [comment]
@redinkinc as others have mentioned this is not the proper place for trouble shooting questions, rather it's to make the developers aware of potential software bugs. Also, as others have mentioned, www.unmethours.com is the proper place to for support questions.

**Comment by redinkinc** [comment]
ok, I will give it a try. I just wondered if this wasn't better be asked to developers than to users. But seems there are also developers on UnmetHours.
Thanks, Fabian
